name: flutter_play_chess
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  chopper: ^4.0.6
  rxdart: ^0.27.4
  flutter_bloc: ^8.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  auto_route: ^4.2.0
  extended_nested_scroll_view: ^5.1.3
  logger: ^1.1.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.1+1
  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  chopper_generator: ^4.0.6
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.11

flutter:
  assets:
    - assets/svg/bg/play_bg.svg

    - assets/svg/icons/notification_bell.svg
    - assets/svg/icons/user.svg
    
    - assets/svg/icons/logo.svg

    - assets/svg/icons/bottom_nav_bar/lesson_active.svg
    - assets/svg/icons/bottom_nav_bar/lesson_not_active.svg

    - assets/svg/icons/bottom_nav_bar/menu_active.svg
    - assets/svg/icons/bottom_nav_bar/menu_not_active.svg

    - assets/svg/icons/bottom_nav_bar/play_active.svg
    - assets/svg/icons/bottom_nav_bar/play_not_active.svg

    - assets/svg/icons/bottom_nav_bar/profile_active.svg
    - assets/svg/icons/bottom_nav_bar/profile_not_active.svg

    - assets/svg/icons/bottom_nav_bar/trophy_active.svg
    - assets/svg/icons/bottom_nav_bar/trophy_not_active.svg

    - assets/svg/icons/eye_hide.svg
    - assets/svg/icons/eye_open.svg
  uses-material-design: true
