// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXjcEyw0NUd_4rxZGkwNavcfmYacGdHLI',
    appId: '1:904413632764:web:38a3131f167e1845969f79',
    messagingSenderId: '904413632764',
    projectId: 'flutter-play-chess',
    authDomain: 'flutter-play-chess.firebaseapp.com',
    storageBucket: 'flutter-play-chess.appspot.com',
    measurementId: 'G-6243YYW2DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABqB-cAFTTEPq0B_e6u1aZKvILwfiYyLM',
    appId: '1:904413632764:android:c96806528d531036969f79',
    messagingSenderId: '904413632764',
    projectId: 'flutter-play-chess',
    storageBucket: 'flutter-play-chess.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtuLpss9nFDAfZyMvZ8JE_dJEyy89LATg',
    appId: '1:904413632764:ios:f3a5c8a46ecb11bb969f79',
    messagingSenderId: '904413632764',
    projectId: 'flutter-play-chess',
    storageBucket: 'flutter-play-chess.appspot.com',
    iosClientId: '904413632764-lp9oqmlp160tvra7h5d80bu380p24avu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPlayChess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtuLpss9nFDAfZyMvZ8JE_dJEyy89LATg',
    appId: '1:904413632764:ios:f3a5c8a46ecb11bb969f79',
    messagingSenderId: '904413632764',
    projectId: 'flutter-play-chess',
    storageBucket: 'flutter-play-chess.appspot.com',
    iosClientId: '904413632764-lp9oqmlp160tvra7h5d80bu380p24avu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPlayChess',
  );
}
